//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaVenta
    {
        public int Id { get; set; }
        public Nullable<int> VentaId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
