//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoCompras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.ListaVenta = new HashSet<ListaVenta>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Foto { get; set; }
        public Nullable<int> CategoriaId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<ListaVenta> ListaVenta { get; set; }
    }
}
